import type { ProductItem } from '../src/types.js';

export const INITIAL_PRODUCTS: ProductItem[] = [
  // --- GAMES: MOBILE LEGENDS ---
  {
    code: 'MLBB5',
    name: 'Mobile Legends 5 Diamonds (Fast)',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Mobile Legends',
    price: 1400,
    sellPrice: 1500,
    note: 'Format: ID (Zone). Masuk 1-3 detik otomatis 24 Jam.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'MLBB12',
    name: 'Mobile Legends 12 Diamonds (Fast)',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Mobile Legends',
    price: 3300,
    sellPrice: 3500,
    note: 'Format: ID (Zone). Masuk 1-3 detik otomatis 24 Jam.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'MLBB50',
    name: 'Mobile Legends 50 Diamonds (Fast)',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Mobile Legends',
    price: 13500,
    sellPrice: 14200,
    note: 'Format: ID (Zone). Masuk 1-3 detik otomatis 24 Jam.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'MLBB86',
    name: 'Mobile Legends 86 Diamonds (Fast)',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Mobile Legends',
    price: 21800,
    sellPrice: 22800,
    note: 'Format: ID (Zone). Masuk 1-3 detik otomatis 24 Jam.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'MLBB172',
    name: 'Mobile Legends 172 Diamonds (Fast)',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Mobile Legends',
    price: 43200,
    sellPrice: 45000,
    note: 'Format: ID (Zone). Masuk 1-3 detik otomatis 24 Jam.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'MLBB257',
    name: 'Mobile Legends 257 Diamonds (Fast)',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Mobile Legends',
    price: 64500,
    sellPrice: 67000,
    note: 'Format: ID (Zone). Masuk 1-3 detik otomatis 24 Jam.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'MLBB706',
    name: 'Mobile Legends 706 Diamonds (Fast)',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Mobile Legends',
    price: 174000,
    sellPrice: 180000,
    note: 'Format: ID (Zone). Masuk 1-3 detik otomatis 24 Jam.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'MLBB_WP',
    name: 'Weekly Diamond Pass Mobile Legends',
    category: 'Games',
    type: 'Membership',
    provider: 'Mobile Legends',
    price: 27500,
    sellPrice: 28500,
    note: 'Klaim harian total 210 Diamonds + 70 COA.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80',
  },

  // --- GAMES: FREE FIRE ---
  {
    code: 'FF50',
    name: 'Free Fire 50 Diamonds',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Free Fire',
    price: 6800,
    sellPrice: 7200,
    note: 'Masukkan User ID Free Fire.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'FF70',
    name: 'Free Fire 70 Diamonds',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Free Fire',
    price: 9200,
    sellPrice: 9800,
    note: 'Masukkan User ID Free Fire.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'FF140',
    name: 'Free Fire 140 Diamonds',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Free Fire',
    price: 18400,
    sellPrice: 19500,
    note: 'Masukkan User ID Free Fire.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'FF355',
    name: 'Free Fire 355 Diamonds',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Free Fire',
    price: 45800,
    sellPrice: 48000,
    note: 'Masukkan User ID Free Fire.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'FF720',
    name: 'Free Fire 720 Diamonds',
    category: 'Games',
    type: 'Diamonds',
    provider: 'Free Fire',
    price: 91500,
    sellPrice: 95000,
    note: 'Masukkan User ID Free Fire.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80',
  },
  {
    code: 'FF_BOOYAH',
    name: 'Free Fire Booyah Pass Premium',
    category: 'Games',
    type: 'Pass',
    provider: 'Free Fire',
    price: 46000,
    sellPrice: 48000,
    note: 'Buka slot hadiah eksklusif musim aktif.',
    status: 'available',
    img_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80',
  },

  // --- GAMES: PUBG MOBILE ---
  {
    code: 'PUBG60',
    name: 'PUBG Mobile 60 UC (Global)',
    category: 'Games',
    type: 'Unknown Cash',
    provider: 'PUBG Mobile',
    price: 14200,
    sellPrice: 15000,
    note: 'Masukkan ID Karakter PUBG.',
    status: 'available',
  },
  {
    code: 'PUBG325',
    name: 'PUBG Mobile 325 UC (Global)',
    category: 'Games',
    type: 'Unknown Cash',
    provider: 'PUBG Mobile',
    price: 69500,
    sellPrice: 72000,
    note: 'Masukkan ID Karakter PUBG.',
    status: 'available',
  },
  {
    code: 'PUBG660',
    name: 'PUBG Mobile 660 UC (Global)',
    category: 'Games',
    type: 'Unknown Cash',
    provider: 'PUBG Mobile',
    price: 139000,
    sellPrice: 145000,
    note: 'Masukkan ID Karakter PUBG.',
    status: 'available',
  },

  // --- PLN TOKEN LISTRIK ---
  {
    code: 'PLN20',
    name: 'PLN Token Listrik Rp 20.000',
    category: 'PLN',
    type: 'Prabayar',
    provider: 'PLN',
    price: 20100,
    sellPrice: 20500,
    note: 'Masukkan No Meter / ID Pelanggan (11-12 digit). Kode Token muncul di riwayat transaksi.',
    status: 'available',
  },
  {
    code: 'PLN50',
    name: 'PLN Token Listrik Rp 50.000',
    category: 'PLN',
    type: 'Prabayar',
    provider: 'PLN',
    price: 50100,
    sellPrice: 50500,
    note: 'Masukkan No Meter / ID Pelanggan. Kode Token langsung terbit.',
    status: 'available',
  },
  {
    code: 'PLN100',
    name: 'PLN Token Listrik Rp 100.000',
    category: 'PLN',
    type: 'Prabayar',
    provider: 'PLN',
    price: 100100,
    sellPrice: 100600,
    note: 'Masukkan No Meter / ID Pelanggan.',
    status: 'available',
  },
  {
    code: 'PLN200',
    name: 'PLN Token Listrik Rp 200.000',
    category: 'PLN',
    type: 'Prabayar',
    provider: 'PLN',
    price: 200100,
    sellPrice: 200700,
    note: 'Masukkan No Meter / ID Pelanggan.',
    status: 'available',
  },
  {
    code: 'PLN500',
    name: 'PLN Token Listrik Rp 500.000',
    category: 'PLN',
    type: 'Prabayar',
    provider: 'PLN',
    price: 500100,
    sellPrice: 500900,
    note: 'Masukkan No Meter / ID Pelanggan.',
    status: 'available',
  },

  // --- PULSA REGULER & DATA INTERNET ---
  {
    code: 'TSEL10',
    name: 'Telkomsel Pulsa Reguler 10.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'TELKOMSEL',
    price: 10250,
    sellPrice: 10600,
    note: 'Menambah masa aktif & pulsa utama.',
    status: 'available',
  },
  {
    code: 'TSEL25',
    name: 'Telkomsel Pulsa Reguler 25.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'TELKOMSEL',
    price: 25100,
    sellPrice: 25500,
    note: 'Menambah masa aktif & pulsa utama.',
    status: 'available',
  },
  {
    code: 'TSEL50',
    name: 'Telkomsel Pulsa Reguler 50.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'TELKOMSEL',
    price: 49800,
    sellPrice: 50300,
    note: 'Menambah masa aktif & pulsa utama.',
    status: 'available',
  },
  {
    code: 'TSEL100',
    name: 'Telkomsel Pulsa Reguler 100.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'TELKOMSEL',
    price: 98500,
    sellPrice: 99500,
    note: 'Menambah masa aktif & pulsa utama.',
    status: 'available',
  },
  {
    code: 'ISAT10',
    name: 'Indosat Ooredoo Pulsa 10.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'INDOSAT',
    price: 10300,
    sellPrice: 10700,
    note: 'Menambah masa aktif Indosat IM3.',
    status: 'available',
  },
  {
    code: 'ISAT25',
    name: 'Indosat Ooredoo Pulsa 25.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'INDOSAT',
    price: 25150,
    sellPrice: 25600,
    note: 'Menambah masa aktif Indosat IM3.',
    status: 'available',
  },
  {
    code: 'ISAT50',
    name: 'Indosat Ooredoo Pulsa 50.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'INDOSAT',
    price: 49850,
    sellPrice: 50400,
    note: 'Menambah masa aktif Indosat IM3.',
    status: 'available',
  },
  {
    code: 'XL10',
    name: 'XL Axiata Pulsa 10.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'XL',
    price: 10250,
    sellPrice: 10650,
    note: 'Pulsa reguler XL Nasional.',
    status: 'available',
  },
  {
    code: 'XL25',
    name: 'XL Axiata Pulsa 25.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'XL',
    price: 25100,
    sellPrice: 25550,
    note: 'Pulsa reguler XL Nasional.',
    status: 'available',
  },
  {
    code: 'XL50',
    name: 'XL Axiata Pulsa 50.000',
    category: 'Pulsa Reguler',
    type: 'Reguler',
    provider: 'XL',
    price: 49750,
    sellPrice: 50350,
    note: 'Pulsa reguler XL Nasional.',
    status: 'available',
  },

  // --- E-MONEY & DOMPET DIGITAL ---
  {
    code: 'DANA10',
    name: 'Saldo DANA Rp 10.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'DANA',
    price: 10200,
    sellPrice: 10600,
    note: 'Masukkan nomor HP akun DANA.',
    status: 'available',
  },
  {
    code: 'DANA20',
    name: 'Saldo DANA Rp 20.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'DANA',
    price: 20200,
    sellPrice: 20600,
    note: 'Masukkan nomor HP akun DANA.',
    status: 'available',
  },
  {
    code: 'DANA50',
    name: 'Saldo DANA Rp 50.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'DANA',
    price: 50200,
    sellPrice: 50700,
    note: 'Masukkan nomor HP akun DANA.',
    status: 'available',
  },
  {
    code: 'DANA100',
    name: 'Saldo DANA Rp 100.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'DANA',
    price: 100200,
    sellPrice: 100800,
    note: 'Masukkan nomor HP akun DANA.',
    status: 'available',
  },
  {
    code: 'GOPAY20',
    name: 'Saldo GoPay Customer Rp 20.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'GO PAY',
    price: 20300,
    sellPrice: 20750,
    note: 'Masukkan nomor HP akun Gojek/GoPay.',
    status: 'available',
  },
  {
    code: 'GOPAY50',
    name: 'Saldo GoPay Customer Rp 50.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'GO PAY',
    price: 50300,
    sellPrice: 50850,
    note: 'Masukkan nomor HP akun Gojek/GoPay.',
    status: 'available',
  },
  {
    code: 'OVO20',
    name: 'Saldo OVO Cash Rp 20.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'OVO',
    price: 20350,
    sellPrice: 20800,
    note: 'Masukkan nomor HP akun OVO.',
    status: 'available',
  },
  {
    code: 'OVO50',
    name: 'Saldo OVO Cash Rp 50.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'OVO',
    price: 50350,
    sellPrice: 50900,
    note: 'Masukkan nomor HP akun OVO.',
    status: 'available',
  },
  {
    code: 'SHOPEE20',
    name: 'Saldo ShopeePay Rp 20.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'SHOPEE PAY',
    price: 20300,
    sellPrice: 20750,
    note: 'Masukkan nomor HP akun Shopee.',
    status: 'available',
  },
  {
    code: 'SHOPEE50',
    name: 'Saldo ShopeePay Rp 50.000',
    category: 'E-Money',
    type: 'Topup',
    provider: 'SHOPEE PAY',
    price: 50300,
    sellPrice: 50850,
    note: 'Masukkan nomor HP akun Shopee.',
    status: 'available',
  },
];
